# Generated by Django 4.2.6 on 2024-01-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='item',
            field=models.CharField(db_column='Item', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='quantity',
            field=models.IntegerField(db_column='Quantity', null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(db_column='Status', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='unitprice',
            field=models.DecimalField(db_column='Unit Price', decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item',
            field=models.CharField(db_column='Item', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(db_column='Quantity', null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unitprice',
            field=models.DecimalField(db_column='Unit Price', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='item',
            field=models.CharField(db_column='Item', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='quantity',
            field=models.IntegerField(db_column='Quantity', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(db_column='Total', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='unitprice',
            field=models.DecimalField(db_column='Unit Price', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='item',
            field=models.CharField(db_column='Item', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='location',
            field=models.TextField(blank=True, db_column='Location'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='status',
            field=models.CharField(db_column='Status', max_length=50, null=True),
        ),
    ]
