# Generated by Django 4.2.6 on 2024-01-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luminex', '0004_alter_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total',
        ),
    ]
