# Generated by Django 4.2.6 on 2024-01-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminex', '0006_invoice_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='address',
            field=models.CharField(db_column='Address', max_length=1024, null=True),
        ),
    ]
